export default {
  COLOR_MAIN: "#EC6345",
  COLOR_WHITE_BACKGROUND: "#fff",
  COLOR_BOX_SHADOW: "rgba(0, 0, 0, 0.2)",

  COLOR_TAB_BAR_ICON: "#AFAFAF",

  COLOR_HEADER: "#fff",

  COLOR_BLUE_TEXT: "#1B6FEE",
  COLOR_GRAY_TEXT: "#959595",
  COLOR_WHITE_TEXT: "#fff",

  COLOR_GRAY_BORDER: "#DEDEDE",

  COLOR_NOT_SELECTED_FILTER: "#EEF1F3",

  COLOR_GRAY_ICON: "#BEBEBE",
};
